const forcasSeguranca = [
  "EXÉRCITO BRASILEIRO - EB",
  "MARINHA DO BRASIL - MB",
  "AGENTE DE TRÂNSITO",
  "OUTROS - SEGURANÇA",
  "POLICIAL MILITAR",
  "POLICIAL FEDERAL",
  "POLICIAL CIVIL",
  "POLICIAL RODOVIÁRIO FEDERAL",
  "GUARDA MUNICIPAL",
  "BOMBEIRO MILITAR",
  "BOMBEIRO CIVIL",
  "FORÇA AÉREA BRASILEIRA - FAB",
  "FUNCIONÁRIO DO SISTEMA DE PRIVAÇÃO DE LIBERDADE",
];
export default forcasSeguranca;
