const trabalhadoresEducacao = [
  "PROFESSOR - ENSINO SUPERIOR",
  "OUTROS - ENSINO SUPERIOR",
  "PROFESSOR - EDUCAÇÃO FUNDAMENTAL I",
  "PROFESSOR - EDUCAÇÃO FUNDAMENTAL II",
  "PROFESSOR - ENSINO MÉDIO",
  "OUTROS - CRECHES, PRÉ-ESCOLAS",
  "PROFESSOR - CRECHES, PRÉ-ESCOLAS",
  "OUTROS - ENSINO FUNDAMENTAL I",
  "OUTROS - ENSINO FUNDAMENTAL II",
  "OUTROS - ENSINO MÉDIO",
  "PROFESSOR - PROFISSIONALIZANTES E EJA",
  "OUTROS - PROFISSIONALIZANTES E EJA",
];
export default trabalhadoresEducacao;
